import { themes as prismThemes } from "prism-react-renderer";
import type { Config } from "@docusaurus/types";
import type * as Preset from "@docusaurus/preset-classic";

const GITHUB_URL = "https://github.com/maitrungduc1410/vivari";
// Every sibling surface (landing at `/`, docs at `/docs/`, studio at `/studio/`)
// lives outside this site's baseUrl. Docusaurus prefixes baseUrl onto any
// path-like link and then route-checks it, so reaching a sibling requires an
// absolute URL, which Docusaurus treats as external.
const SITE_URL = "https://vivari.run";

// Why this is a second Docusaurus site rather than a `/blog` route inside
// sites/docs: the landing owns the origin root, and a Docusaurus build always
// emits index.html/404.html/assets/ at its own baseUrl root. Serving both docs
// and the blog from one build would mean baseUrl `/`, whose index.html would
// overwrite the landing's. Two builds, two baseUrls, no collision — and the blog
// gets its own theme for free (see src/css/custom.css).
const config: Config = {
  title: "Vivari engineering",
  tagline: "Teardowns of the browser-side Node runtime behind Vivari",
  favicon: "img/favicon.svg",

  url: SITE_URL,
  baseUrl: "/blog/",

  organizationName: "maitrungduc1410",
  projectName: "vivari",

  onBrokenLinks: "throw",

  i18n: {
    defaultLocale: "en",
    locales: ["en"],
  },

  markdown: {
    mermaid: false,
    hooks: {
      onBrokenMarkdownLinks: "warn",
    },
  },

  presets: [
    [
      "classic",
      {
        // Docs live in their own build at /docs/.
        docs: false,
        blog: {
          // Serve posts at the site root, i.e. `/blog/<slug>` once baseUrl is
          // applied, rather than `/blog/blog/<slug>`.
          routeBasePath: "/",
          path: "./posts",
          blogTitle: "Vivari engineering",
          blogDescription:
            "Teardowns of the browser-side Node runtime behind Vivari.",
          blogSidebarTitle: "All posts",
          blogSidebarCount: "ALL",
          showReadingTime: true,
          editUrl: `${GITHUB_URL}/tree/master/sites/blog/`,
          // A post with no <!-- truncate --> would dump its whole body onto the
          // list page and into the feed; fail the build instead.
          onUntruncatedBlogPosts: "throw",
          feedOptions: {
            type: "all",
            title: "Vivari engineering",
            description:
              "Teardowns of the browser-side Node runtime behind Vivari.",
            copyright: "MIT-licensed.",
            xslt: true,
          },
        },
        theme: {
          customCss: "./src/css/custom.css",
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    // PNG, not SVG: X, Slack, LinkedIn and Discord all refuse to render an SVG
    // og:image. Generated by `npm run og` at the repo root (scripts/og-cards.mjs).
    image: "img/social-card.png",
    colorMode: {
      defaultMode: "dark",
      respectPrefersColorScheme: true,
    },
    navbar: {
      title: "Vivari",
      logo: {
        alt: "Vivari",
        src: "img/logo.svg",
      },
      items: [
        { to: "/", label: "Blog", position: "left", activeBasePath: "/" },
        // Absolute URLs so they escape this site's baseUrl (see SITE_URL above).
        { href: `${SITE_URL}/docs/`, label: "Docs", position: "left" },
        { href: `${SITE_URL}/studio/`, label: "Studio", position: "left" },
        { href: `${SITE_URL}/`, label: "Home", position: "left" },
        {
          href: GITHUB_URL,
          label: "GitHub",
          position: "right",
        },
      ],
    },
    footer: {
      style: "dark",
      links: [
        {
          title: "Writing",
          items: [
            { label: "All posts", to: "/" },
            { label: "Tags", to: "/tags" },
            { label: "Archive", to: "/archive" },
            { label: "RSS", href: `${SITE_URL}/blog/rss.xml` },
          ],
        },
        {
          title: "Docs",
          items: [
            { label: "Introduction", href: `${SITE_URL}/docs/` },
            { label: "Getting started", href: `${SITE_URL}/docs/getting-started` },
            { label: "How it works", href: `${SITE_URL}/docs/how-it-works` },
          ],
        },
        {
          title: "Product",
          items: [
            { label: "Home", href: `${SITE_URL}/` },
            { label: "Studio", href: `${SITE_URL}/studio/` },
            { label: "GitHub", href: GITHUB_URL },
            {
              label: "@vivari/core on npm",
              href: "https://www.npmjs.com/package/@vivari/core",
            },
          ],
        },
      ],
      copyright: `MIT-licensed. Built with Docusaurus.`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      additionalLanguages: ["bash", "json", "jsx", "tsx"],
    },
  } satisfies Preset.ThemeConfig,
};

export default config;