// Minimal end-to-end tour of the @vivari/core SDK:
//   1. boot a browser-native Node.js VM
//   2. mount a file tree, run a script, and stream its stdout
//   3. start an in-VM HTTP server and preview it in an <iframe>
//
// The page must be cross-origin isolated (COOP + COEP) — see vite.config.ts.

import { Vivari, VivariError, type FileSystemTree, type OutputStream } from "@vivari/core";

const $ = <T extends HTMLElement>(id: string) => document.getElementById(id) as T;

const runStatus = $("run-status");
const runOutput = $<HTMLPreElement>("run-output");
const previewStatus = $("preview-status");
const previewFrame = $<HTMLIFrameElement>("preview");

function append(pre: HTMLPreElement, chunk: string) {
  pre.textContent += chunk;
  pre.scrollTop = pre.scrollHeight;
}

// Pipe a process's merged stdout/stderr into a <pre>. `proc.stdout` / `proc.stderr`
// are separate views of the same output if you need them apart.
async function stream(proc: { output: OutputStream }, pre: HTMLPreElement) {
  for await (const chunk of proc.output) append(pre, chunk);
}

const project: FileSystemTree = {
  "package.json": {
    file: {
      contents: JSON.stringify(
        { name: "vivari-example", type: "module", private: true },
        null,
        2,
      ),
    },
  },
  // A one-shot script for demo #1.
  "hello.js": {
    file: {
      contents: [
        "import os from 'node:os';",
        "console.log('Hello from Node ' + process.version + ' — in your browser!');",
        "console.log('platform:', process.platform, '| arch:', process.arch);",
        "console.log('cwd:', process.cwd());",
        "for (let i = 1; i <= 3; i++) console.log('tick ' + i);",
      ].join("\n"),
    },
  },
  // A tiny HTTP server for demo #2.
  "server.js": {
    file: {
      contents: [
        "import { createServer } from 'node:http';",
        "const server = createServer((req, res) => {",
        "  res.setHeader('content-type', 'text/html; charset=utf-8');",
        "  res.end('<h1>Served from inside your browser 🎉</h1>' +",
        "    '<p>Request: ' + req.method + ' ' + req.url + '</p>' +",
        "    '<p>This HTML was generated by a Node.js HTTP server running in a Web Worker.</p>');",
        "});",
        "server.listen(3111, () => console.log('listening on http://localhost:3111'));",
      ].join("\n"),
    },
  },
};

async function main() {
  runStatus.textContent = "booting the Vivari kernel…";

  // devtools defaults to false for embedders; serviceWorkerUrl defaults to /sw.js.
  const vivari = await Vivari.boot();
  await vivari.mount(project);

  // --- Demo 1: run a script to completion, streaming its output ---
  runStatus.textContent = "running: node hello.js";
  const hello = await vivari.spawn("node", ["hello.js"]);
  await stream(hello, runOutput);
  const code = await hello.exit;
  runStatus.textContent = `node hello.js exited with code ${code}`;

  // --- Demo 2: start a server and preview it ---
  previewStatus.textContent = "starting: node server.js";
  vivari.on("server-ready", (port, url) => {
    previewStatus.textContent = `server listening on in-VM port ${port} → ${url}`;
    previewFrame.src = url;
    previewFrame.hidden = false;
  });
  // Long-running: don't await exit. Its logs share the same <pre> as demo #1.
  const server = await vivari.spawn("node", ["server.js"]);
  void stream(server, runOutput);
}

main().catch((err) => {
  // Everything the SDK throws is a VivariError with a machine-readable `code`
  // (here: ERR_NOT_ISOLATED, ERR_BOOT_TIMEOUT, ERR_WORKER, …), so a real app can
  // branch on it instead of matching the message text.
  const code = err instanceof VivariError ? err.code : "UNKNOWN";
  const message = err instanceof Error ? err.message : String(err);
  runStatus.textContent = "Failed to boot Vivari.";
  append(runOutput, `\n[${code}] ${message}\n`);
  previewStatus.textContent = "unavailable";
  // The most common cause is a page that isn't cross-origin isolated.
  console.error(err);
});