import { themes as prismThemes } from "prism-react-renderer";
import type { Config } from "@docusaurus/types";
import type * as Preset from "@docusaurus/preset-classic";

const GITHUB_URL = "https://github.com/maitrungduc1410/vivari";
// The sibling apps (landing at `/`, blog at `/blog/`, studio at `/studio/`) live
// at the origin root, outside the docs baseUrl (`/docs/`). Docusaurus prefixes
// baseUrl onto any path-like link (`to`, `href`, `pathname://`) and route-checks
// it, so linking to them requires an absolute URL, which Docusaurus treats as
// external (no baseUrl, no broken-link check).
const SITE_URL = "https://vivari.run";

const config: Config = {
  title: "Vivari",
  tagline: "Run Node.js projects fully client-side in the browser",
  favicon: "img/favicon.svg",

  // Deployed as part of a single Cloudflare Pages site: the landing lives at `/`,
  // the studio at `/studio/`, and these docs at `/docs/`.
  url: SITE_URL,
  baseUrl: "/docs/",

  organizationName: "maitrungduc1410",
  projectName: "vivari",

  onBrokenLinks: "throw",

  i18n: {
    defaultLocale: "en",
    locales: ["en"],
  },

  markdown: {
    mermaid: false,
    hooks: {
      onBrokenMarkdownLinks: "warn",
    },
  },

  presets: [
    [
      "classic",
      {
        docs: {
          // Serve docs at the site root (i.e. `/docs/` once baseUrl is applied)
          // instead of `/docs/docs/`.
          routeBasePath: "/",
          sidebarPath: "./sidebars.ts",
          editUrl: `${GITHUB_URL}/tree/master/sites/docs/`,
        },
        // The engineering blog is its own Docusaurus build at `/blog/`
        // (sites/blog), so this site stays docs-only.
        blog: false,
        theme: {
          customCss: "./src/css/custom.css",
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    // PNG, not SVG: X, Slack, LinkedIn and Discord all refuse to render an SVG
    // og:image. Generated by `npm run og` at the repo root (scripts/og-cards.mjs).
    image: "img/social-card.png",
    colorMode: {
      defaultMode: "dark",
      respectPrefersColorScheme: true,
    },
    navbar: {
      title: "Vivari",
      logo: {
        alt: "Vivari",
        src: "img/logo.svg",
      },
      items: [
        // Absolute URLs so they escape the docs baseUrl and reach the sibling apps
        // at the origin root (see SITE_URL note above).
        { href: `${SITE_URL}/blog/`, label: "Blog", position: "left" },
        { href: `${SITE_URL}/studio/`, label: "Studio", position: "left" },
        { href: `${SITE_URL}/`, label: "Home", position: "left" },
        {
          href: GITHUB_URL,
          label: "GitHub",
          position: "right",
        },
      ],
    },
    footer: {
      style: "dark",
      links: [
        {
          title: "Docs",
          items: [
            { label: "Introduction", to: "/" },
            { label: "Getting started", to: "/getting-started" },
            { label: "Core API", to: "/core-api" },
            { label: "React", to: "/react" },
          ],
        },
        {
          title: "Product",
          items: [
            { label: "Home", href: `${SITE_URL}/` },
            { label: "Studio", href: `${SITE_URL}/studio/` },
          ],
        },
        {
          title: "More",
          items: [
            { label: "Blog", href: `${SITE_URL}/blog/` },
            { label: "RSS", href: `${SITE_URL}/blog/rss.xml` },
            { label: "GitHub", href: GITHUB_URL },
            { label: "@vivari/core on npm", href: "https://www.npmjs.com/package/@vivari/core" },
          ],
        },
      ],
      copyright: `MIT-licensed. Built with Docusaurus.`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      additionalLanguages: ["bash", "json", "jsx", "tsx"],
    },
  } satisfies Preset.ThemeConfig,
};

export default config;