// The two pure parts of scripts/assemble-site.mjs: the `_headers` text it emits,
// and the list of runtime-fetched assets it asserts are present.
//
// They live here so spike-site-headers.mjs can assert on them without running an
// assembly — which would need all five app builds on disk and would overwrite
// dist/. That matters more than the usual "extract for testability": the
// duplicate-COOP bug this module exists to gate is a pure function of the string
// below, invisible to every local server, and it reached code review precisely
// because nothing could reach it without a full Cloudflare deploy.

// ── _headers ────────────────────────────────────────────────────────────────
//
// Cross-origin isolation, scoped to every surface that runs the runtime. The
// studio and the /embed/ playground need SharedArrayBuffer directly; the docs
// (/docs/*) and the blog (/blog/*) need it because they host the /embed/ iframe,
// and an iframe is only cross-origin isolated when its top-level document is
// too. The cost is that both sites must serve every image same-origin, since
// COEP blocks third-party subresources that don't send CORP. The landing (/)
// stays free of COEP. Preview responses (/preview/<port>/) are synthesized by
// the Service Worker, which stamps their isolation headers itself.
//
// The DevTools frontend needs an entry of its OWN even though it is same-origin.
// Under COEP:require-corp a nested DOCUMENT is not covered by the same-origin
// exemption that subresources get: it must send require-corp (or credentialless)
// itself, or Chrome refuses the frame outright with the "<host> refused to
// connect" error page. `/devtools-host.html` is hoisted OUT of /studio/ to the
// origin root by assemble-site.mjs, so the `/studio/*` rule no longer reaches
// it. Both the `.html` and the extensionless form are listed because Pages'
// clean URLs redirect `/x.html` to `/x`, and the rule must match the URL that
// finally answers 200. Locally none of this shows up: the Vite dev server stamps
// isolation on EVERY response (studio vite.config.ts `swScope()`), so
// devtools-host.html inherits it there.
//
// ONE RULE PER HEADER PER PATH. Pages applies every matching rule and joins a
// header set twice with a comma, and COOP/COEP are structured-field *items*:
// `same-origin, same-origin` is a list, fails to parse, and a failed parse means
// `unsafe-none`. So a second block repeating the value on a path it already
// covers does not reinforce isolation — it removes it, taking SharedArrayBuffer
// and the whole runtime with it. `/studio/*` and `/embed/*` are the single
// source of COI for their subtrees; every narrower block under them carries
// Cache-Control and nothing else.
//
// Cache policy for content-hashed output, and ONLY for content-hashed output.
// Cloudflare Pages' default is `max-age=14400, must-revalidate` on everything,
// which is the wrong pair twice over: it expires a file whose name already
// guarantees its contents, so a visitor four hours later re-downloads the whole
// cold path; and until then every reload still spends a conditional request per
// asset to be told 304. `immutable` removes both, and is correct precisely
// because Vite emits `<name>-<hash>.<ext>` — a changed byte is a changed URL.
// So it must never widen past `<app>/assets/*`, and in particular never to
// `<app>/vendor/*`, whose URLs are stable while their contents are not: the
// locks and snapshots under it are re-resolved on every CI checkout, so
// `immutable` there would pin a returning visitor to an old tree forever. (The
// Service Worker's cache-first prefix list is narrowed for the same reason —
// see `prefixes` in packages/studio/vite.config.ts.) The HTML revalidates too:
// it is the file that names the hashes.
const IMMUTABLE = "  Cache-Control: public, max-age=31536000, immutable";
const REVALIDATE = "  Cache-Control: public, max-age=0, must-revalidate";
const COI = `  Cross-Origin-Opener-Policy: same-origin
  Cross-Origin-Embedder-Policy: require-corp`;

export const SITE_HEADERS = `# Generated by scripts/assemble-site.mjs — do not edit by hand.
# Cross-origin isolation comes from the /studio/* and /embed/* blocks ONLY.
# Repeating it in a narrower block would comma-join the header and void it.
/studio/assets/*
${IMMUTABLE}

/embed/assets/*
${IMMUTABLE}

/studio/
${REVALIDATE}

/studio/index.html
${REVALIDATE}

/studio/*
${COI}

/embed/*
${COI}

/docs/*
${COI}

/blog/*
${COI}

/devtools-host.html
${COI}

/devtools-host
${COI}

/devtools/*
${COI}

/sw.js
  Service-Worker-Allowed: /
${COI}
`;

// ── kernel-fetchable assets ─────────────────────────────────────────────────
//
// Assets the kernel fetches at runtime whose absence raises nothing.
//
// The SPA fallback (`/studio/* /studio/index.html 200`) is why this list has to
// exist. A missing file under /studio/ does not 404 — it answers `200 text/html`
// with the shell, and every consumer of these assets treats a parse failure as
// "the feature is off" and carries on in silence. That is not hypothetical:
// production has been serving the landing page's HTML for
// `vendor/depcache/index.json` (disabling the single largest install
// optimisation in the product for every visitor) and for
// `vendor/sqlite/sqlite3.wasm` (because cloudflare-build.sh omitted
// `vendor:sqlite`, which prebuild:studio includes). Both shipped, and nothing
// anywhere went red.
//
// Declared rather than discovered, so an asset that stops being produced fails
// here instead of quietly vanishing. `optional` is for producers that are opt-in
// by design — reported, never fatal — and the point of listing them at all is
// that a reported absence is visible where a missing line is not.
export const KERNEL_ASSETS = [
  // The vendored package managers + toolchain (scripts/vendor-*.mjs, run by
  // `prebuild:studio`). Fetched by kernel-worker.ts's vendorUrl().
  { rel: "vendor/npm-pack.bin" },
  { rel: "vendor/yarn-pack.bin" },
  { rel: "vendor/pnpm-pack.bin" },
  { rel: "vendor/corepack-pack.bin" },
  { rel: "vendor/tsgo-pack.bin" },
  { rel: "vendor/sqlite/sqlite3.wasm" },
  { rel: "vendor/pyodide", dir: true },
  { rel: "vendor/ruff", dir: true },
  // Producers that a build may legitimately not run.
  { rel: "vendor/depcache/index.json", optional: true },
  { rel: "vendor/locks/index.json", optional: true },
  // The app itself. A studio shell without an entry chunk is a blank page.
  { rel: "index.html" },
  { rel: "assets", dir: true },
];

/**
 * Check KERNEL_ASSETS under each app directory of an assembled `dist`.
 *
 * Both surfaces resolve vendor assets relative to their own base, so both need
 * the tree (assemble-site.mjs copies the studio's into /embed/).
 *
 * @param {string} dist absolute path to the assembled output
 * @param {(rel: string) => boolean} exists non-empty-file/dir probe, injectable
 *   so a spike can drive the matrix without materialising 60 MB of fixtures
 * @returns {{ missing: string[], present: number, absentOptional: string[] }}
 */
export function checkKernelAssets(dist, exists) {
  const missing = [];
  const absentOptional = [];
  let present = 0;
  for (const appDir of ["studio", "embed"]) {
    for (const asset of KERNEL_ASSETS) {
      const rel = `${appDir}/${asset.rel}`;
      if (exists(dist ? `${dist}/${rel}` : rel, asset)) { present++; continue; }
      if (asset.optional) absentOptional.push(`/${rel}`);
      else missing.push(`/${rel}`);
    }
  }
  return { missing, present, absentOptional };
}
