// Assemble the SECOND Cloudflare Pages project (mode B — separate preview origin).
//
//   dist-preview/            <- the preview origin root (e.g. vivari-preview.pages.dev)
//     sw.js                  <- the preview Service Worker (proxies preview HTTP to the kernel)
//     __vv-bridge.html       <- hidden bridge doc the IDE iframes to hand the SW a port
//     vv-devtools/chobitsu.js<- the in-preview DevTools (CDP) backend (absolute-pathed by the SW)
//     _headers               <- COEP:credentialless + CORP:cross-origin (+ Service-Worker-Allowed)
//
// This origin runs NO kernel and NO studio UI. It is pure static hosting: the SW
// relays every preview request over a MessagePort to the kernel living in the IDE
// tab (see packages/core/src/bridge.ts setupPreviewBridge + packages/studio/public/
// __vv-bridge.html). Deploy `dist-preview/` as its own Pages project and point the
// IDE build at it via VITE_PREVIEW_ORIGIN=https://<that-origin>.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(fileURLToPath(new URL("../", import.meta.url)));
const STUDIO = path.join(root, "packages/studio/dist");
const out = path.join(root, "dist-preview");

if (!fs.existsSync(STUDIO)) {
  console.error(`\u2717 missing studio build: ${STUDIO}`);
  console.error("  Build the studio first (see scripts/cloudflare-build.sh).");
  process.exit(1);
}

fs.rmSync(out, { recursive: true, force: true });
fs.mkdirSync(out, { recursive: true });

// The exact set of files the preview origin must serve. Everything else a preview
// page loads is proxied by the SW into the VM; only these are real static assets.
//   __vv-bridge.html      — hidden iframe the editor loads to register the SW + relay a port
//   __vv-preview-boot.html — first-party boot page for a preview opened in its OWN tab
const FILES = ["sw.js", "__vv-bridge.html", "__vv-preview-boot.html"];
const DIRS = ["vv-devtools"]; // chobitsu.js (the CDP backend, absolute-pathed by the SW)

for (const name of FILES) {
  const from = path.join(STUDIO, name);
  if (!fs.existsSync(from)) {
    console.error(`\u2717 missing ${name} in the studio build (${from})`);
    process.exit(1);
  }
  fs.copyFileSync(from, path.join(out, name));
  console.log(`\u2192 ${name}`);
}

for (const name of DIRS) {
  const from = path.join(STUDIO, name);
  if (!fs.existsSync(from)) {
    // DevTools are optional; a preview still works without the CDP backend.
    console.warn(`\u26a0 optional ${name}/ not found in the studio build — skipping`);
    continue;
  }
  fs.cpSync(from, path.join(out, name), { recursive: true });
  console.log(`\u2192 ${name}/`);
}

// Headers for the preview origin. Previews are a DIFFERENT origin from the IDE, so
// the SW stamps each proxied response with CORP:cross-origin + COEP:credentialless
// (see handlePreview); these static-file headers make the SW itself, the bridge
// doc, and chobitsu.js embeddable cross-origin under the IDE's COEP:require-corp.
// COOP:same-origin isolates a preview opened as its OWN top-level tab. The SW must
// be allowed to claim root scope.
const ISOLATE = `  Cross-Origin-Opener-Policy: same-origin
  Cross-Origin-Embedder-Policy: credentialless
  Cross-Origin-Resource-Policy: cross-origin`;
const headers = `# Generated by scripts/assemble-preview.mjs — do not edit by hand.
/*
${ISOLATE}

/sw.js
  Service-Worker-Allowed: /
${ISOLATE}
`;
fs.writeFileSync(path.join(out, "_headers"), headers);

// SPA-style fallback (200 rewrite, NOT a redirect) so a preview opened in its own
// top-level tab isn't a hard 404 before a Service Worker controls it. When the SW
// IS controlling it intercepts `/preview/*` first, so the embedded editor preview
// is unaffected; this only fires for a first-party standalone tab whose SW isn't
// visible yet (storage partitioning), where the boot page registers it and reloads.
fs.writeFileSync(path.join(out, "_redirects"), "/preview/* /__vv-preview-boot.html 200\n");

console.log(`\u2713 assembled preview origin into ${path.relative(root, out)}/`);