// Assemble the single Cloudflare Pages deploy from the three app builds:
//
//   dist/            <- landing (sites/landing/dist)  ->  served at /
//   dist/docs/       <- docs    (sites/docs/build)     ->  served at /docs/
//   dist/studio/     <- studio  (packages/studio/dist) ->  served at /studio/
//
// The preview Service Worker and its runtime asset tree are hoisted to the origin
// root (/sw.js, /vv-devtools/*, /devtools/*, /devtools-host.html) because the SW
// claims root scope and hard-codes those absolute paths. Only the studio UI is
// namespaced under /studio/. Finally we emit _headers (COOP/COEP scoped to the
// studio + SW) and a _redirects SPA fallback for /studio/*.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(fileURLToPath(new URL("../", import.meta.url)));
const dist = path.join(root, "dist");

const LANDING = path.join(root, "sites/landing/dist");
const DOCS = path.join(root, "sites/docs/build");
const STUDIO = path.join(root, "packages/studio/dist");

// Studio runtime paths that must live at the origin root, not under /studio/.
const HOIST = ["sw.js", "vv-devtools", "devtools", "devtools-host.html"];

function requireDir(p, label) {
  if (!fs.existsSync(p)) {
    console.error(`\u2717 missing ${label} build: ${p}`);
    console.error("  Run the full build first (see scripts/cloudflare-build.sh).");
    process.exit(1);
  }
}

requireDir(LANDING, "landing");
requireDir(DOCS, "docs");
requireDir(STUDIO, "studio");

fs.rmSync(dist, { recursive: true, force: true });
fs.mkdirSync(dist, { recursive: true });

// 1. Landing at the root.
fs.cpSync(LANDING, dist, { recursive: true });

// 2. Docs under /docs/.
fs.cpSync(DOCS, path.join(dist, "docs"), { recursive: true });

// 3. Studio under /studio/.
const studioOut = path.join(dist, "studio");
fs.cpSync(STUDIO, studioOut, { recursive: true });

// 3b. Hoist the SW runtime tree from /studio/ up to the origin root.
for (const name of HOIST) {
  const from = path.join(studioOut, name);
  const to = path.join(dist, name);
  if (!fs.existsSync(from)) continue;
  fs.rmSync(to, { recursive: true, force: true });
  fs.renameSync(from, to);
  console.log(`\u2192 hoisted ${name} to origin root`);
}

// 4. Headers: scope cross-origin isolation to the studio + the Service Worker.
const headers = `# Generated by scripts/assemble-site.mjs — do not edit by hand.
# Cross-origin isolation is scoped to the studio (which needs SharedArrayBuffer)
# and the preview Service Worker. The landing (/) and docs (/docs/) stay free of
# COEP so they can load anything. Preview responses (/preview/<port>/) are
# synthesized by the SW, which stamps their isolation headers itself.
/studio/*
  Cross-Origin-Opener-Policy: same-origin
  Cross-Origin-Embedder-Policy: require-corp

/sw.js
  Service-Worker-Allowed: /
  Cross-Origin-Opener-Policy: same-origin
  Cross-Origin-Embedder-Policy: require-corp
`;
fs.writeFileSync(path.join(dist, "_headers"), headers);

// 5. SPA fallback so deep links inside the studio resolve to its shell. Static
// files (assets, favicon) are served before this rule ever applies.
fs.writeFileSync(path.join(dist, "_redirects"), "/studio/* /studio/index.html 200\n");

console.log(`\u2713 assembled site into ${path.relative(root, dist)}/`);
