// Assemble the single Cloudflare Pages deploy from the three app builds:
//
//   dist/            <- landing (sites/landing/dist)  ->  served at /
//   dist/docs/       <- docs    (sites/docs/build)     ->  served at /docs/
//   dist/studio/     <- studio  (packages/studio/dist) ->  served at /studio/
//
// The preview Service Worker and its runtime asset tree are hoisted to the origin
// root (/sw.js, /vv-devtools/*, /devtools/*, /devtools-host.html) because the SW
// claims root scope and hard-codes those absolute paths. Only the studio UI is
// namespaced under /studio/. Finally we emit _headers (COOP/COEP scoped to the
// studio + SW) and a _redirects SPA fallback for /studio/*.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(fileURLToPath(new URL("../", import.meta.url)));
const dist = path.join(root, "dist");

const LANDING = path.join(root, "sites/landing/dist");
const DOCS = path.join(root, "sites/docs/build");
const STUDIO = path.join(root, "packages/studio/dist");
const EMBED = path.join(root, "sites/embed/dist");

// Studio runtime paths that must live at the origin root, not under /studio/.
const HOIST = ["sw.js", "vv-devtools", "devtools", "devtools-host.html"];

function requireDir(p, label) {
  if (!fs.existsSync(p)) {
    console.error(`\u2717 missing ${label} build: ${p}`);
    console.error("  Run the full build first (see scripts/cloudflare-build.sh).");
    process.exit(1);
  }
}

requireDir(LANDING, "landing");
requireDir(DOCS, "docs");
requireDir(STUDIO, "studio");
requireDir(EMBED, "embed");

fs.rmSync(dist, { recursive: true, force: true });
fs.mkdirSync(dist, { recursive: true });

// 1. Landing at the root.
fs.cpSync(LANDING, dist, { recursive: true });

// 2. Docs under /docs/.
fs.cpSync(DOCS, path.join(dist, "docs"), { recursive: true });

// 3. Studio under /studio/.
const studioOut = path.join(dist, "studio");
fs.cpSync(STUDIO, studioOut, { recursive: true });

// 3b. Hoist the SW runtime tree from /studio/ up to the origin root.
for (const name of HOIST) {
  const from = path.join(studioOut, name);
  const to = path.join(dist, name);
  if (!fs.existsSync(from)) continue;
  fs.rmSync(to, { recursive: true, force: true });
  fs.renameSync(from, to);
  console.log(`\u2192 hoisted ${name} to origin root`);
}

// 3c. Embed playground under /embed/ (iframed by the docs live examples). It
// registers the same root /sw.js, so no per-app copy is needed here.
const embedOut = path.join(dist, "embed");
fs.cpSync(EMBED, embedOut, { recursive: true });
// The embed's standalone build emits its own /embed/sw.js; the real SW is the
// hoisted root /sw.js, so drop the redundant copy to avoid a stale duplicate.
fs.rmSync(path.join(embedOut, "sw.js"), { force: true });

// 4. Headers: scope cross-origin isolation to every surface that runs the
// runtime. The studio and the /embed/ playground need SharedArrayBuffer directly;
// the docs (/docs/*) need it because they host the /embed/ iframe, and an iframe
// is only cross-origin isolated when its top-level document is too. The landing
// (/) stays free of COEP. Preview responses (/preview/<port>/) are synthesized by
// the SW, which stamps their isolation headers itself.
const COI = `  Cross-Origin-Opener-Policy: same-origin
  Cross-Origin-Embedder-Policy: require-corp`;
const headers = `# Generated by scripts/assemble-site.mjs — do not edit by hand.
/studio/*
${COI}

/embed/*
${COI}

/docs/*
${COI}

/sw.js
  Service-Worker-Allowed: /
${COI}
`;
fs.writeFileSync(path.join(dist, "_headers"), headers);

// 5. SPA fallback so deep links inside the studio resolve to its shell. Static
// files (assets, favicon) are served before this rule ever applies.
fs.writeFileSync(path.join(dist, "_redirects"), "/studio/* /studio/index.html 200\n");

console.log(`\u2713 assembled site into ${path.relative(root, dist)}/`);
