// Regenerate packages/runtime/node/bindings/llhttp/llhttp-wasm-data.js from a
// pinned undici release. We reuse undici's already-compiled llhttp.wasm (the
// same upstream llhttp, https://github.com/nodejs/llhttp) instead of standing up
// a wasi-sdk/clang toolchain just to rebuild an identical artifact.
//
//   node scripts/vendor-llhttp.mjs                 # download undici@<VERSION>
//   node scripts/vendor-llhttp.mjs --from <file>   # read a local llhttp-wasm.js
//
// The non-SIMD build is vendored deliberately: it instantiates everywhere a
// worker can run WebAssembly, with no SIMD feature-detection dance.
//
// Provenance / license: llhttp is MIT (Fedor Indutny & collaborators); undici is
// MIT (Node.js contributors). We ship only the compiled byte payload as base64.

import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, writeFileSync, rmSync, readdirSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const UNDICI_VERSION = "6.21.3";
const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(
  HERE,
  "..",
  "packages",
  "runtime",
  "node",
  "bindings",
  "llhttp",
  "llhttp-wasm-data.js",
);

function readFromArg() {
  const i = process.argv.indexOf("--from");
  if (i === -1) return null;
  const p = process.argv[i + 1];
  if (!p) throw new Error("--from needs a path to undici's lib/llhttp/llhttp-wasm.js");
  return { file: p, version: "local" };
}

function downloadUndici() {
  const dir = mkdtempSync(path.join(tmpdir(), "vendor-llhttp-"));
  try {
    execFileSync("npm", ["pack", `undici@${UNDICI_VERSION}`], { cwd: dir, stdio: "inherit" });
    const tgz = readdirSync(dir).find((f) => f.endsWith(".tgz"));
    execFileSync("tar", ["-xzf", tgz], { cwd: dir });
    return {
      file: path.join(dir, "package", "lib", "llhttp", "llhttp-wasm.js"),
      version: `undici@${UNDICI_VERSION}`,
      cleanup: dir,
    };
  } catch (e) {
    rmSync(dir, { recursive: true, force: true });
    throw e;
  }
}

const src = readFromArg() || downloadUndici();
try {
  // undici's llhttp-wasm.js is `module.exports = Buffer.from('<base64>', 'base64')`.
  const text = readFileSync(src.file, "utf8");
  const m = text.match(/Buffer\.from\('([A-Za-z0-9+/=]+)'/);
  if (!m) throw new Error(`could not find base64 payload in ${src.file}`);
  const base64 = m[1];
  const bytes = Buffer.from(base64, "base64");
  if (bytes.subarray(0, 4).toString("latin1") !== "\0asm") {
    throw new Error("decoded payload is not a WebAssembly module (bad magic)");
  }

  const out = `// AUTO-GENERATED by scripts/vendor-llhttp.mjs — DO NOT EDIT BY HAND.
//
// llhttp compiled to WebAssembly, vendored from ${src.version}
// (lib/llhttp/llhttp-wasm.js). Upstream: https://github.com/nodejs/llhttp (MIT),
// packaged by https://github.com/nodejs/undici (MIT). Non-SIMD build.
//
// Regenerate: node scripts/vendor-llhttp.mjs
//
// ${bytes.length} bytes.

export const LLHTTP_WASM_VERSION = ${JSON.stringify(src.version)};
export const LLHTTP_WASM_BASE64 =
  ${JSON.stringify(base64)};
`;
  writeFileSync(OUT, out);
  console.log(`wrote ${OUT} (${bytes.length} wasm bytes, from ${src.version})`);
} finally {
  if (src.cleanup) rmSync(src.cleanup, { recursive: true, force: true });
}
